Problem Set 1: Fun with Dummies
===============================
## Joe Sutherland
### September 19, 2016

# Question 1

In [1]:
n <- 6
t <- 4
nt <- n * t

## Question 2

In [87]:
l.t <- matrix(1, nrow = t)
l.n <- matrix(1, nrow = n)
l.nt <- matrix(1, nrow = nt)

## Question 3

In [88]:
I.n <- diag(1, n)
I.t <- diag(1, t)

## Question 4

In [89]:
idums <- I.n %x% l.t
idums

[,1] [,2] [,3] [,4] [,5] [,6]
 [1,] 1    0    0    0    0    0   
 [2,] 1    0    0    0    0    0   
 [3,] 1    0    0    0    0    0   
 [4,] 1    0    0    0    0    0   
 [5,] 0    1    0    0    0    0   
 [6,] 0    1    0    0    0    0   
 [7,] 0    1    0    0    0    0   
 [8,] 0    1    0    0    0    0   
 [9,] 0    0    1    0    0    0   
[10,] 0    0    1    0    0    0   
[11,] 0    0    1    0    0    0   
[12,] 0    0    1    0    0    0   
[13,] 0    0    0    1    0    0   
[14,] 0    0    0    1    0    0   
[15,] 0    0    0    1    0    0   
[16,] 0    0    0    1    0    0   
[17,] 0    0    0    0    1    0   
[18,] 0    0    0    0    1    0   
[19,] 0    0    0    0    1    0   
[20,] 0    0    0    0    1    0   
[21,] 0    0    0    0    0    1   
[22,] 0    0    0    0    0    1   
[23,] 0    0    0    0    0    1   
[24,] 0    0    0    0    0    1

# Question 5

In [90]:
m.n <- t(idums) %*% idums
solve(m.n)

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 0.25 0.00 0.00 0.00 0.00 0.00
[2,] 0.00 0.25 0.00 0.00 0.00 0.00
[3,] 0.00 0.00 0.25 0.00 0.00 0.00
[4,] 0.00 0.00 0.00 0.25 0.00 0.00
[5,] 0.00 0.00 0.00 0.00 0.25 0.00
[6,] 0.00 0.00 0.00 0.00 0.00 0.25

We find a symmetric matrix of ratios.

## Question 6

In [91]:
tdums <- l.t %x% I.n
tdums

[,1] [,2] [,3] [,4] [,5] [,6]
 [1,] 1    0    0    0    0    0   
 [2,] 0    1    0    0    0    0   
 [3,] 0    0    1    0    0    0   
 [4,] 0    0    0    1    0    0   
 [5,] 0    0    0    0    1    0   
 [6,] 0    0    0    0    0    1   
 [7,] 1    0    0    0    0    0   
 [8,] 0    1    0    0    0    0   
 [9,] 0    0    1    0    0    0   
[10,] 0    0    0    1    0    0   
[11,] 0    0    0    0    1    0   
[12,] 0    0    0    0    0    1   
[13,] 1    0    0    0    0    0   
[14,] 0    1    0    0    0    0   
[15,] 0    0    1    0    0    0   
[16,] 0    0    0    1    0    0   
[17,] 0    0    0    0    1    0   
[18,] 0    0    0    0    0    1   
[19,] 1    0    0    0    0    0   
[20,] 0    1    0    0    0    0   
[21,] 0    0    1    0    0    0   
[22,] 0    0    0    1    0    0   
[23,] 0    0    0    0    1    0   
[24,] 0    0    0    0    0    1

## Question 7

In [92]:
m.t <- t(tdums) %*% tdums
solve(m.t)

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 0.25 0.00 0.00 0.00 0.00 0.00
[2,] 0.00 0.25 0.00 0.00 0.00 0.00
[3,] 0.00 0.00 0.25 0.00 0.00 0.00
[4,] 0.00 0.00 0.00 0.25 0.00 0.00
[5,] 0.00 0.00 0.00 0.00 0.25 0.00
[6,] 0.00 0.00 0.00 0.00 0.00 0.25

We find a symmetric matrix of ratios that is identical, in this case, to the matrix found from inverting the cross-sectional unit dummies.

## Question 8

In [93]:
tidums <- cbind(idums, tdums)
m.ti <- t(tidums) %*% tidums
solve(m.ti)

ERROR: Error in solve.default(m.ti): Lapack routine dgesv: system is exactly singular: U[12,12] = 0


We find that we cannot invert the matrix because it is singular (the determinant of the matrix is zero). A determinant of zero suggests that the solution set contains solutions that aren't linearly independent. _I.e._, one or more of the dummy rows or columns is/are exactly expressible as a linear combination of all or some other its rows or columns. We know that this is the case, because we haven't dropped any of the dummies.

## Question 9

In [94]:
tidums <- tidums[,-12]
tidums

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
 [1,] 1    0    0    0    0    0    1    0    0    0     0    
 [2,] 1    0    0    0    0    0    0    1    0    0     0    
 [3,] 1    0    0    0    0    0    0    0    1    0     0    
 [4,] 1    0    0    0    0    0    0    0    0    1     0    
 [5,] 0    1    0    0    0    0    0    0    0    0     1    
 [6,] 0    1    0    0    0    0    0    0    0    0     0    
 [7,] 0    1    0    0    0    0    1    0    0    0     0    
 [8,] 0    1    0    0    0    0    0    1    0    0     0    
 [9,] 0    0    1    0    0    0    0    0    1    0     0    
[10,] 0    0    1    0    0    0    0    0    0    1     0    
[11,] 0    0    1    0    0    0    0    0    0    0     1    
[12,] 0    0    1    0    0    0    0    0    0    0     0    
[13,] 0    0    0    1    0    0    1    0    0    0     0    
[14,] 0    0    0    1    0    0    0    1    0    0     0    
[15,] 0    0    0    1    0    0    0    0    1    0     0    
[16,] 0    0    0    1    0    0    0    0    0    1     0    
[17,] 0    0    0    0    1    0    0    0    0    0     1    
[18,] 0    0    0    0    1    0    0    0    0    0     0    
[19,] 0    0    0    0    1    0    1    0    0    0     0    
[20,] 0    0    0    0    1    0    0    1    0    0     0    
[21,] 0    0    0    0    0    1    0    0    1    0     0    
[22,] 0    0    0    0    0    1    0    0    0    1     0    
[23,] 0    0    0    0    0    1    0    0    0    0     1    
[24,] 0    0    0    0    0    1    0    0    0    0     0

## Question 10

In [95]:
m.ti2 <- t(tidums) %*% tidums
solve(m.ti2)

[,1]   [,2]       [,3]       [,4]   [,5]       [,6]       [,7]      
 [1,]  0.625  0.2500000  0.2500000  0.375  0.2500000  0.2500000 -0.3750000
 [2,]  0.250  0.4583333  0.1666667  0.250  0.2083333  0.1666667 -0.2916667
 [3,]  0.250  0.1666667  0.4583333  0.250  0.1666667  0.2083333 -0.2083333
 [4,]  0.375  0.2500000  0.2500000  0.625  0.2500000  0.2500000 -0.3750000
 [5,]  0.250  0.2083333  0.1666667  0.250  0.4583333  0.1666667 -0.2916667
 [6,]  0.250  0.1666667  0.2083333  0.250  0.1666667  0.4583333 -0.2083333
 [7,] -0.375 -0.2916667 -0.2083333 -0.375 -0.2916667 -0.2083333  0.5833333
 [8,] -0.375 -0.2916667 -0.2083333 -0.375 -0.2916667 -0.2083333  0.3333333
 [9,] -0.375 -0.2083333 -0.2916667 -0.375 -0.2083333 -0.2916667  0.2916667
[10,] -0.375 -0.2083333 -0.2916667 -0.375 -0.2083333 -0.2916667  0.2916667
[11,] -0.250 -0.2500000 -0.2500000 -0.250 -0.2500000 -0.2500000  0.2500000
      [,8]       [,9]       [,10]      [,11]
 [1,] -0.3750000 -0.3750000 -0.3750000 -0.25
 [2,] -0.2916667 -0.2083333 -0.2083333 -0.25
 [3,] -0.2083333 -0.2916667 -0.2916667 -0.25
 [4,] -0.3750000 -0.3750000 -0.3750000 -0.25
 [5,] -0.2916667 -0.2083333 -0.2083333 -0.25
 [6,] -0.2083333 -0.2916667 -0.2916667 -0.25
 [7,]  0.3333333  0.2916667  0.2916667  0.25
 [8,]  0.5833333  0.2916667  0.2916667  0.25
 [9,]  0.2916667  0.5833333  0.3333333  0.25
[10,]  0.2916667  0.3333333  0.5833333  0.25
[11,]  0.2500000  0.2500000  0.2500000  0.50

Because the matrix is now invertible, we yield the inverted matrix. We find that we are able to invert the matrix because none of its rows or columns are exactly expressible as a linear combination of all or some other its rows or columns (because we dropped one!).

## Question 11

In [96]:
tidums <- cbind(rep(1, nrow(tidums)), tidums)
solve(t(tidums) %*% tidums)

ERROR: Error in solve.default(t(tidums) %*% tidums): system is computationally singular: reciprocal condition number = 6.53072e-18


We find that we cannot invert the matrix because it is singular. It is singular because we included the intercept term, causing one or more of its vectors to be exactly expressible as a linear combination of all or some of its other vectors.

In order to solve the matrix, we must also drop one of the cross-sectional dummies.

In [97]:
tidums <- tidums[,-7]
solve(t(tidums) %*% tidums)

[,1]       [,2]          [,3]          [,4]          [,5]         
 [1,]  0.4583333 -2.083333e-01 -2.916667e-01 -2.500000e-01 -2.083333e-01
 [2,] -0.2083333  5.833333e-01  2.916667e-01  2.500000e-01  3.333333e-01
 [3,] -0.2916667  2.916667e-01  5.833333e-01  2.500000e-01  2.916667e-01
 [4,] -0.2500000  2.500000e-01  2.500000e-01  5.000000e-01  2.500000e-01
 [5,] -0.2083333  3.333333e-01  2.916667e-01  2.500000e-01  5.833333e-01
 [6,] -0.2916667  2.916667e-01  3.333333e-01  2.500000e-01  2.916667e-01
 [7,] -0.2083333 -1.666667e-01 -8.333333e-02  2.312965e-17 -1.666667e-01
 [8,] -0.2083333 -1.666667e-01 -8.333333e-02  2.312965e-17 -1.666667e-01
 [9,] -0.2916667 -8.333333e-02  8.333333e-02 -2.312965e-17 -8.333333e-02
[10,] -0.2916667 -8.333333e-02  8.333333e-02 -2.312965e-17 -8.333333e-02
[11,] -0.2500000  1.387779e-17 -4.163336e-17 -5.551115e-17  1.387779e-17
      [,6]          [,7]          [,8]          [,9]          [,10]        
 [1,] -2.916667e-01 -2.083333e-01 -2.083333e-01 -2.916667e-01 -2.916667e-01
 [2,]  2.916667e-01 -1.666667e-01 -1.666667e-01 -8.333333e-02 -8.333333e-02
 [3,]  3.333333e-01 -8.333333e-02 -8.333333e-02  8.333333e-02  8.333333e-02
 [4,]  2.500000e-01  9.251859e-18  9.251859e-18 -7.401487e-17 -6.013708e-17
 [5,]  2.916667e-01 -1.666667e-01 -1.666667e-01 -8.333333e-02 -8.333333e-02
 [6,]  5.833333e-01 -8.333333e-02 -8.333333e-02  8.333333e-02  8.333333e-02
 [7,] -8.333333e-02  5.833333e-01  3.333333e-01  2.916667e-01  2.916667e-01
 [8,] -8.333333e-02  3.333333e-01  5.833333e-01  2.916667e-01  2.916667e-01
 [9,]  8.333333e-02  2.916667e-01  2.916667e-01  5.833333e-01  3.333333e-01
[10,]  8.333333e-02  2.916667e-01  2.916667e-01  3.333333e-01  5.833333e-01
[11,] -4.163336e-17  2.500000e-01  2.500000e-01  2.500000e-01  2.500000e-01
      [,11]        
 [1,] -2.500000e-01
 [2,] -1.572816e-17
 [3,] -4.625929e-17
 [4,] -5.319819e-17
 [5,] -2.081668e-17
 [6,] -4.163336e-17
 [7,]  2.500000e-01
 [8,]  2.500000e-01
 [9,]  2.500000e-01
[10,]  2.500000e-01
[11,]  5.000000e-01